// Generated by gencpp from file color_detect_srvs/colorSrv.msg
// DO NOT EDIT!


#ifndef COLOR_DETECT_SRVS_MESSAGE_COLORSRV_H
#define COLOR_DETECT_SRVS_MESSAGE_COLORSRV_H

#include <ros/service_traits.h>


#include <color_detect_srvs/colorSrvRequest.h>
#include <color_detect_srvs/colorSrvResponse.h>


namespace color_detect_srvs
{

struct colorSrv
{

typedef colorSrvRequest Request;
typedef colorSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct colorSrv
} // namespace color_detect_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_detect_srvs::colorSrv > {
  static const char* value()
  {
    return "8ee3ae6e55f5ddfc2f446e412119bc69";
  }

  static const char* value(const ::color_detect_srvs::colorSrv&) { return value(); }
};

template<>
struct DataType< ::color_detect_srvs::colorSrv > {
  static const char* value()
  {
    return "color_detect_srvs/colorSrv";
  }

  static const char* value(const ::color_detect_srvs::colorSrv&) { return value(); }
};


// service_traits::MD5Sum< ::color_detect_srvs::colorSrvRequest> should match
// service_traits::MD5Sum< ::color_detect_srvs::colorSrv >
template<>
struct MD5Sum< ::color_detect_srvs::colorSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_detect_srvs::colorSrv >::value();
  }
  static const char* value(const ::color_detect_srvs::colorSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_detect_srvs::colorSrvRequest> should match
// service_traits::DataType< ::color_detect_srvs::colorSrv >
template<>
struct DataType< ::color_detect_srvs::colorSrvRequest>
{
  static const char* value()
  {
    return DataType< ::color_detect_srvs::colorSrv >::value();
  }
  static const char* value(const ::color_detect_srvs::colorSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_detect_srvs::colorSrvResponse> should match
// service_traits::MD5Sum< ::color_detect_srvs::colorSrv >
template<>
struct MD5Sum< ::color_detect_srvs::colorSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_detect_srvs::colorSrv >::value();
  }
  static const char* value(const ::color_detect_srvs::colorSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_detect_srvs::colorSrvResponse> should match
// service_traits::DataType< ::color_detect_srvs::colorSrv >
template<>
struct DataType< ::color_detect_srvs::colorSrvResponse>
{
  static const char* value()
  {
    return DataType< ::color_detect_srvs::colorSrv >::value();
  }
  static const char* value(const ::color_detect_srvs::colorSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_DETECT_SRVS_MESSAGE_COLORSRV_H
