// Generated by gencpp from file color_detect_srvs/colorSrvRequest.msg
// DO NOT EDIT!


#ifndef COLOR_DETECT_SRVS_MESSAGE_COLORSRVREQUEST_H
#define COLOR_DETECT_SRVS_MESSAGE_COLORSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace color_detect_srvs
{
template <class ContainerAllocator>
struct colorSrvRequest_
{
  typedef colorSrvRequest_<ContainerAllocator> Type;

  colorSrvRequest_()
    : position_srv(0)  {
    }
  colorSrvRequest_(const ContainerAllocator& _alloc)
    : position_srv(0)  {
  (void)_alloc;
    }



   typedef int16_t _position_srv_type;
  _position_srv_type position_srv;





  typedef boost::shared_ptr< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct colorSrvRequest_

typedef ::color_detect_srvs::colorSrvRequest_<std::allocator<void> > colorSrvRequest;

typedef boost::shared_ptr< ::color_detect_srvs::colorSrvRequest > colorSrvRequestPtr;
typedef boost::shared_ptr< ::color_detect_srvs::colorSrvRequest const> colorSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator1> & lhs, const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position_srv == rhs.position_srv;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator1> & lhs, const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_detect_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b914a1496294ef741808bfcc7d68343";
  }

  static const char* value(const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b914a1496294ef7ULL;
  static const uint64_t static_value2 = 0x41808bfcc7d68343ULL;
};

template<class ContainerAllocator>
struct DataType< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_detect_srvs/colorSrvRequest";
  }

  static const char* value(const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16  position_srv\n"
"\n"
;
  }

  static const char* value(const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_srv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct colorSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_detect_srvs::colorSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_detect_srvs::colorSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "position_srv: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position_srv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_DETECT_SRVS_MESSAGE_COLORSRVREQUEST_H
