// Generated by gencpp from file main_control/main2nav.msg
// DO NOT EDIT!


#ifndef MAIN_CONTROL_MESSAGE_MAIN2NAV_H
#define MAIN_CONTROL_MESSAGE_MAIN2NAV_H

#include <ros/service_traits.h>


#include <main_control/main2navRequest.h>
#include <main_control/main2navResponse.h>


namespace main_control
{

struct main2nav
{

typedef main2navRequest Request;
typedef main2navResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct main2nav
} // namespace main_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main_control::main2nav > {
  static const char* value()
  {
    return "7efbb833c5f53a4a2e67aab06606b39f";
  }

  static const char* value(const ::main_control::main2nav&) { return value(); }
};

template<>
struct DataType< ::main_control::main2nav > {
  static const char* value()
  {
    return "main_control/main2nav";
  }

  static const char* value(const ::main_control::main2nav&) { return value(); }
};


// service_traits::MD5Sum< ::main_control::main2navRequest> should match
// service_traits::MD5Sum< ::main_control::main2nav >
template<>
struct MD5Sum< ::main_control::main2navRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main_control::main2nav >::value();
  }
  static const char* value(const ::main_control::main2navRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_control::main2navRequest> should match
// service_traits::DataType< ::main_control::main2nav >
template<>
struct DataType< ::main_control::main2navRequest>
{
  static const char* value()
  {
    return DataType< ::main_control::main2nav >::value();
  }
  static const char* value(const ::main_control::main2navRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main_control::main2navResponse> should match
// service_traits::MD5Sum< ::main_control::main2nav >
template<>
struct MD5Sum< ::main_control::main2navResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main_control::main2nav >::value();
  }
  static const char* value(const ::main_control::main2navResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_control::main2navResponse> should match
// service_traits::DataType< ::main_control::main2nav >
template<>
struct DataType< ::main_control::main2navResponse>
{
  static const char* value()
  {
    return DataType< ::main_control::main2nav >::value();
  }
  static const char* value(const ::main_control::main2navResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_CONTROL_MESSAGE_MAIN2NAV_H
