(cl:defpackage nav-srv
  (:use )
  (:export
   "SERVICE_MSG"
   "<SERVICE_MSG-REQUEST>"
   "SERVICE_MSG-REQUEST"
   "<SERVICE_MSG-RESPONSE>"
   "SERVICE_MSG-RESPONSE"
   "MAIN2NAV"
   "<MAIN2NAV-REQUEST>"
   "MAIN2NAV-REQUEST"
   "<MAIN2NAV-RESPONSE>"
   "MAIN2NAV-RESPONSE"
  ))

