// Generated by gencpp from file nav/main2nav.msg
// DO NOT EDIT!


#ifndef NAV_MESSAGE_MAIN2NAV_H
#define NAV_MESSAGE_MAIN2NAV_H

#include <ros/service_traits.h>


#include <nav/main2navRequest.h>
#include <nav/main2navResponse.h>


namespace nav
{

struct main2nav
{

typedef main2navRequest Request;
typedef main2navResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct main2nav
} // namespace nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav::main2nav > {
  static const char* value()
  {
    return "7efbb833c5f53a4a2e67aab06606b39f";
  }

  static const char* value(const ::nav::main2nav&) { return value(); }
};

template<>
struct DataType< ::nav::main2nav > {
  static const char* value()
  {
    return "nav/main2nav";
  }

  static const char* value(const ::nav::main2nav&) { return value(); }
};


// service_traits::MD5Sum< ::nav::main2navRequest> should match
// service_traits::MD5Sum< ::nav::main2nav >
template<>
struct MD5Sum< ::nav::main2navRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav::main2nav >::value();
  }
  static const char* value(const ::nav::main2navRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav::main2navRequest> should match
// service_traits::DataType< ::nav::main2nav >
template<>
struct DataType< ::nav::main2navRequest>
{
  static const char* value()
  {
    return DataType< ::nav::main2nav >::value();
  }
  static const char* value(const ::nav::main2navRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav::main2navResponse> should match
// service_traits::MD5Sum< ::nav::main2nav >
template<>
struct MD5Sum< ::nav::main2navResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav::main2nav >::value();
  }
  static const char* value(const ::nav::main2navResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav::main2navResponse> should match
// service_traits::DataType< ::nav::main2nav >
template<>
struct DataType< ::nav::main2navResponse>
{
  static const char* value()
  {
    return DataType< ::nav::main2nav >::value();
  }
  static const char* value(const ::nav::main2navResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_MESSAGE_MAIN2NAV_H
