// Generated by gencpp from file nav/Service_msg.msg
// DO NOT EDIT!


#ifndef NAV_MESSAGE_SERVICE_MSG_H
#define NAV_MESSAGE_SERVICE_MSG_H

#include <ros/service_traits.h>


#include <nav/Service_msgRequest.h>
#include <nav/Service_msgResponse.h>


namespace nav
{

struct Service_msg
{

typedef Service_msgRequest Request;
typedef Service_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service_msg
} // namespace nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav::Service_msg > {
  static const char* value()
  {
    return "86301fa8233c7fe1657e8060a290c050";
  }

  static const char* value(const ::nav::Service_msg&) { return value(); }
};

template<>
struct DataType< ::nav::Service_msg > {
  static const char* value()
  {
    return "nav/Service_msg";
  }

  static const char* value(const ::nav::Service_msg&) { return value(); }
};


// service_traits::MD5Sum< ::nav::Service_msgRequest> should match
// service_traits::MD5Sum< ::nav::Service_msg >
template<>
struct MD5Sum< ::nav::Service_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav::Service_msg >::value();
  }
  static const char* value(const ::nav::Service_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav::Service_msgRequest> should match
// service_traits::DataType< ::nav::Service_msg >
template<>
struct DataType< ::nav::Service_msgRequest>
{
  static const char* value()
  {
    return DataType< ::nav::Service_msg >::value();
  }
  static const char* value(const ::nav::Service_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav::Service_msgResponse> should match
// service_traits::MD5Sum< ::nav::Service_msg >
template<>
struct MD5Sum< ::nav::Service_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav::Service_msg >::value();
  }
  static const char* value(const ::nav::Service_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav::Service_msgResponse> should match
// service_traits::DataType< ::nav::Service_msg >
template<>
struct DataType< ::nav::Service_msgResponse>
{
  static const char* value()
  {
    return DataType< ::nav::Service_msg >::value();
  }
  static const char* value(const ::nav::Service_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_MESSAGE_SERVICE_MSG_H
