// Generated by gencpp from file nav/Service_msgRequest.msg
// DO NOT EDIT!


#ifndef NAV_MESSAGE_SERVICE_MSGREQUEST_H
#define NAV_MESSAGE_SERVICE_MSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav
{
template <class ContainerAllocator>
struct Service_msgRequest_
{
  typedef Service_msgRequest_<ContainerAllocator> Type;

  Service_msgRequest_()
    : direction(0)
    , velocity(0)
    , rotation(0)  {
    }
  Service_msgRequest_(const ContainerAllocator& _alloc)
    : direction(0)
    , velocity(0)
    , rotation(0)  {
  (void)_alloc;
    }



   typedef int16_t _direction_type;
  _direction_type direction;

   typedef int16_t _velocity_type;
  _velocity_type velocity;

   typedef int16_t _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::nav::Service_msgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav::Service_msgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Service_msgRequest_

typedef ::nav::Service_msgRequest_<std::allocator<void> > Service_msgRequest;

typedef boost::shared_ptr< ::nav::Service_msgRequest > Service_msgRequestPtr;
typedef boost::shared_ptr< ::nav::Service_msgRequest const> Service_msgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav::Service_msgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav::Service_msgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav::Service_msgRequest_<ContainerAllocator1> & lhs, const ::nav::Service_msgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.velocity == rhs.velocity &&
    lhs.rotation == rhs.rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav::Service_msgRequest_<ContainerAllocator1> & lhs, const ::nav::Service_msgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nav::Service_msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav::Service_msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav::Service_msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav::Service_msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav::Service_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav::Service_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav::Service_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "717d6bf27c8d24b77022a79e91c76f8e";
  }

  static const char* value(const ::nav::Service_msgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x717d6bf27c8d24b7ULL;
  static const uint64_t static_value2 = 0x7022a79e91c76f8eULL;
};

template<class ContainerAllocator>
struct DataType< ::nav::Service_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav/Service_msgRequest";
  }

  static const char* value(const ::nav::Service_msgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav::Service_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 direction\n"
"int16 velocity\n"
"int16 rotation\n"
;
  }

  static const char* value(const ::nav::Service_msgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav::Service_msgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.velocity);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Service_msgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav::Service_msgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav::Service_msgRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int16_t>::stream(s, indent + "  ", v.direction);
    s << indent << "velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "rotation: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_MESSAGE_SERVICE_MSGREQUEST_H
